version: '3.8'

services:
  app:
    image: 'licencemanager:latest'
    restart: always
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/licencemanager'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'lozinka'
      SPRING_JPA_HIBERNATE_DDL_AUTO: 'update'
      SPRING_JPA_SHOW_SQL: 'true'
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: 'com.mysql.cj.jdbc.Driver'
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    image: 'mysql:latest'
    restart: always
    environment:
      MYSQL_DATABASE: 'licencemanager'
      MYSQL_PASSWORD: 'lozinka'
      MYSQL_ROOT_PASSWORD: 'lozinka'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
